### ISSUE TITLE
Compatibility to new ANSLUTA version

### ISSUE THREAD

**Issue by jondoe1337** [tjanson/IKEA-Ansluta#1]
Just a question if you have tried your code against the newer version of the ANSLUTA which uses a 2,4 GHz transmitter: http://www.ikea.com/de/de/catalog/products/90300773/

**Comment by tjanson** [comment]
Nope, I haven’t tried that. In fact, I didn’t pursue this project any further than documented in the README, since I ended up not automating the kitchen lights (yet?).

At first glance that version of the ANSLUTA seems to be control the lights’ three states "on/dimmed/off" rather than simply "on/off", so the coding must differ at the very least in order to accomodate that extra control signal.

**Comment by jondoe1337** [comment]
Thx for the information.

**Comment by white-gecko** [comment]
@jondoe1337 did you find any documentation about the 2.4 GHz version?

**Comment by white-gecko** [comment]
Only thing what I could find so far: https://fccid.io/FHO-YH-KZQ-FS

**Comment by jondoe1337** [comment]
@white-gecko sorry no. I also didn't deal with this topic anymore.

**Comment by mdeverdelhan** [comment]
@white-gecko See https://github.com/NDBCK/Ansluta-Remote-Controller
